### ISSUE TITLE
ICU and iconv explained

### ISSUE THREAD

**Issue by ghost** [grayed/bsd-upstreaming#4]
As I tried to get a hold on what is right and what is wrong :) on the iconv checks which sometimes need adaption to make them work, I've looked up the necessary stuff.

Below the configuration where it is used in qtcore, basically it is an either ICU - or - iconv, whereby ICU takes precedence. As long as you use ICU, there is no need for iconv really working. A reason for that though might be on small embedded systems to use the native iconv to avoid having icu installed.

qtbase/src/corelib/codecs/codecs.pri:

contains(QT_CONFIG,icu) {
    HEADERS += \
        codecs/qicucodec_p.h
    SOURCES += \
        codecs/qicucodec.cpp
} else {
...
    unix:!qnx:!mac:!ios:!linux-android-\* {
            contains(QT_CONFIG,iconv) {
                    HEADERS += codecs/qiconvcodec_p.h
                    SOURCES += codecs/qiconvcodec.cpp
            } else:contains(QT_CONFIG,gnu-libiconv) {
                    HEADERS += codecs/qiconvcodec_p.h
                    SOURCES += codecs/qiconvcodec.cpp
                    DEFINES += GNU_LIBICONV
                    LIBS_PRIVATE *= -liconv
            } else:contains(QT_CONFIG,sun-libiconv) {
                    HEADERS += codecs/qiconvcodec_p.h
                    SOURCES += codecs/qiconvcodec.cpp
                    DEFINES += GNU_LIBICONV
            }
,...

**Comment by ghost** [comment]
Vadim's qtbug report link:

https://bugreports.qt.io/browse/QTBUG-43291

The problem is related to the following (to make this really work at least for detecting, even if it's not used by ports):
- FreeBSD: has iconv in libc, so system iconv test works. But only if libiconv from gnu is not installed (FreeBSD 10 up)
- FreeBSD libiconv from gnu test fails due to wrong const char\* /char\* breakage. The port uses the "system" syntax, so a define would be needed to fix detecting gnu-iconv. The system one isn't found anymore because of the include path /usr/local/include being treated before the system, so if gnu iconv is installed, that takes precedence. In Qt4 ports, there was a patch fixing that:
  [root@w530 /usr/ports/devel/qt4-corelib/files]# cat patch-config.tests_unix_gnu-libiconv_gnu-libiconv.cpp 
  --- config.tests/unix/gnu-libiconv/gnu-libiconv.cpp.orig        2014-04-10 18:37:08 UTC
  +++ config.tests/unix/gnu-libiconv/gnu-libiconv.cpp
  @@ -48,7 +48,7 @@ int main(int, char **)
  {
     iconv_t x = iconv_open("", "");
-    const char *inp;
-    char *inp;
   char *outp;
   size_t inbytes, outbytes;
   iconv(x, &inp, &inbytes, &outp, &outbytes);
  [root@w530 /usr/ports/devel/qt4-corelib/files]
- OpenBSD: has libiconv (gnu) from ports, same problem like FreeBSD ports with parameters.
  http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/x11/qt5/patches/patch-qtbase_config_tests_unix_iconv_iconv_pro

The patch uses the gnu libiconv.so though, so the fix is at the wrong place. The fix should be in the gnu iconv test code like FreeBSD, then linking works.
- NetBSD: 
  http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/x11/qt5-qtbase/patches/patch-config.tests_unix_iconv_iconv.cpp
  NetBSD uses the GNU syntax with const char*, so the patch "reverses" the system iconv.

**Comment by ghost** [comment]
Patch for correct detection and behavior:
https://codereview.qt-project.org/#/c/160727/

**Comment by krytarowski** [comment]
Thank you for taking it.

**Comment by ghost** [comment]
One problem I couldn't solve yet is that whenever libiconv is installed (mostly on user systems already), configure picks it up instead of the libc version, because /usr/local/include is always included first. Then you end up with linker errors on the posix test as -liconv is missing. However, you want to use the posix version where available.
